transform_means: [0.4914, 0.4822, 0.4465]
transform_stds: [0.2470, 0.2435, 0.2616]

one_cycle_lr_div_factor: 100
one_cycle_lr_final_div_factor: 100
one_cycle_lr_anneal_strategy: "cos"
one_cycle_lr_verbose: False
one_cycle_lr_pct_start: 10